collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.7489362
  brandStrength: 0.4827185
  lightness: 0.6680851
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  rhythmicContrast: 0.4744681
typography_spectrum: 0.4432982
layout_spectrum: 1
name: DreamTreeCollective.net
